version: '3'

services:
  api:
    image: api  # Substitua pelo nome da imagem Flask que você construiu
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgresdb
      - mongodb
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    networks:
      - mynetwork

  postgresdb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./POC-SQL.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - tcc

  mongodb:
    networks:
      - tcc
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"

networks:
  tcc:
    driver: bridge

volumes:
  pg_data:
