version: '3'

services:
  api:
    container_name: api
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgresdb
      - mongodb
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    networks:
      - tcc

  postgresdb:
    image: postgres:alpine
    container_name: postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5400:5432'
    volumes:
      - ./POC-SQL.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - tcc

  mongodb:
    networks:
      - tcc
    container_name: mongodb
    image: mongo
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27017:27017"

networks:
  tcc:
    driver: bridge

